# yaml-language-server: $schema=../../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
  netzmacht.contao_toolkit.alias_generator.default: 'netzmacht.contao_toolkit.data.alias_generator.factory.default_factory'

services:
  _defaults:
    public: false

  netzmacht.contao_toolkit.listeners.create_formatter_subscriber:
    class: Netzmacht\Contao\Toolkit\Dca\Formatter\Subscriber\CreateFormatterSubscriber
    arguments:
      - !tagged_iterator 'netzmacht.contao_toolkit.dca.formatter'
      - !tagged_iterator 'netzmacht.contao_toolkit.dca.formatter.pre_filter'
      - !tagged_iterator 'netzmacht.contao_toolkit.dca.formatter.post_filter'
      - '@netzmacht.contao_toolkit.dca.formatter.options'
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.contao_toolkit.dca.create_formatter', method: 'handle' }

  netzmacht.contao_toolkit.listeners.register_models:
    class: Netzmacht\Contao\Toolkit\DependencyInjection\Listener\RegisterContaoModelsListener
    public: true
    arguments:
      - []
    tags:
      - { name: 'contao.hook', hook: 'initializeSystem', method: 'onInitializeSystem', priority: 100 }

  netzmacht.contao_toolkit.listeners.set_operation_data_attribute:
    class: Netzmacht\Contao\Toolkit\Dca\Listener\SetOperationDataAttributeListener
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@contao.routing.scope_matcher'
    tags:
      - { name: 'contao.hook', hook: 'loadDataContainer', method: 'onLoadDataContainer' }

  Netzmacht\Contao\Toolkit\Dca\Listener\Save\GenerateAliasListener:
    public: true
    arguments:
      - '@service_container'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '%netzmacht.contao_toolkit.alias_generator.default%'

  netzmacht.contao_toolkit.dca.listeners.alias_generator:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Save\GenerateAliasListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Save\SlugAliasListener:
    public: true
    arguments:
      - '@contao.slug'
      - '@database_connection'
      - '@netzmacht.contao_toolkit.dca.manager'
    tags:
      - { name: 'netzmacht.contao_toolkit.dca.auto_callback', key: 'alias_generator', slot: 'save_callback', method: 'onSaveCallback' }

  netzmacht.contao_toolkit.dca.listeners.slug_alias_generator:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Save\SlugAliasListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PopupWizardListener:
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.template_renderer'
      - '@translator'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@security.csrf.token_manager'
      - '@router'
      - '%contao.csrf_token_name%'
    tags:
      - { name: 'netzmacht.contao_toolkit.dca.auto_callback', key: 'popup_wizard', slot: 'wizard', method: 'onWizardCallback' }

  netzmacht.contao_toolkit.dca.listeners.popup_wizard:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PopupWizardListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Options\TemplateOptionsListener:
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@Contao\CoreBundle\Twig\Finder\FinderFactory'
    tags:
      - { name: 'netzmacht.contao_toolkit.dca.auto_callback', key: 'template_options', slot: 'options_callback', method: 'onOptionsCallback' }

  netzmacht.contao_toolkit.dca.listeners.template_options:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Options\TemplateOptionsListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\RegisterFieldCallbacksListener:
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@contao.routing.scope_matcher'
      - []
    tags:
      - { name: 'contao.hook', hook: 'loadDataContainer', method: 'onLoadDataContainer' }
